### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by josh-** [JakeGinnivan/WebPack-React-Starter#1]
The `npm start` script currently only supports Windows shell environments when configuring the port that the server should listen on.

I suggest we set the port in a manner that will allow the project to be developed on non-Windows platforms, which I have demonstrated in [this commit](https://github.com/josh-/WebPack-React-Starter/commit/b1e70d0038a0876261cd2fe8cb20a12d1f02670f).

**Comment by JakeGinnivan** [comment]
My plan was to introduce https://www.npmjs.com/package/better-npm-run

I think I should actually introduce it earlier though to make sure everything is xplat by default?

**Comment by josh-** [comment]
better-npm-run looks good, I really don't have a preference.

I like the project you've got here, but use OS X so would definitely encourage cross-platform from the start.

**Comment by JakeGinnivan** [comment]
Have rebased this into the universal react branch, check it out @josh-
